spring:
  kafka:
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${MSK_USER_NAME}" password="${MSK_PASSWORD}";
        mechanism: SCRAM-SHA-512
      security:
        protocol: SASL_SSL